apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  annotations:
    app.openshift.io/vcs-uri: https://github.com/globex-retail/gateway.git?ref=HEAD
    app.openshift.io/connects-to: |
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"catalog"}]
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: app-gateway
    app.openshift.io/runtime: nodejs
  name: gateway
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/part-of: app-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/part-of: app-gateway
    spec:
      containers:
      - image:      "quay.io/globex/gateway:main-1c2041fe8470a802d6670417327c7bdce200541f"
        imagePullPolicy: Always
        name: gateway
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: COOLSTORE_GW_ENDPOINT
            value: catalog-dev
      serviceAccountName: default
status: {}
