apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catalog-scc
  creationTimestamp: null
subjects:
  - kind: ServiceAccount
    name: default
    subjects: ${ARGOCD_APP_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io